name: Arjun context variable demo
on: push
jobs:
  context-demo:
    name: demo of the context is happening
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "this workflow is triggered by ${{ github.actor}}"
          echo "this reposotory name is ${{ github.repository}}"
