name: Deploy HTML to S3

on: workflow_dispatch

jobs:
  
  banao:
   
    runs-on: ubuntu-latest

    
    steps:
    
      - name: First step
        run: echo "This is test for github action"
      
      - name: Deployment Complete
        run: |
          echo "CloudPipe website deployed successfully."
          echo "this is end"
