name: Hello Arjun

on: workflow_dispatch

jobs:
  
  banao:
   
    runs-on: ubuntu-latest

    
    steps:
    
      - name: First step
        run: echo "This is test for github action"
      
      - name: Second Step
        run: |
          echo "this is for multi steps"
          echo "this is another line"
