name: Deploy HTML to S3

on: workflow_dispatch

jobs:
  
  banao:
   
    runs-on: ubuntu-latest

    
    steps:
    
      - name: First step
        run: echo "This is test for github action"

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deployment Completed
        run: |
          echo "CloudPipe website deployed successfully."
          echo "this is end"
