name: Morning Output demo
on: push

jobs:
  my_first_job:
  name: My first job
  my_second_job:
  name: My second job
  
  steps:
    - name: step One
      run: echo "version = 0.0.1 >>$GitHub_Output
