name: I got it
on: workflow_dispatch
jobs:
  working:
    runs-on: ubuntu-latest
    steps:
      - name: First cycle
        run: echo "This first action"
      - name: Second Cycle
        run: |
        echo " bla bla bla"
        echo "la la la la la la"
      

