name: Deploy Website
on: push

jobs:
  deploy:
    name: isla-arjun
    runs-on: ubuntu-latest
    
    steps:
      - name: runs for Arjun
        if: github.actor
        run: echo "actions/checkout@v4"
        
        
        
      
      

