name: Deploy Website
on: workflow_dispatch

jobs:
  deploy:
    name: Deploy Static website on AWS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        run: echo "actions/checkout@v4"
      
      

